name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis relevance

      - name: Install Node.js (optional, if needed for your build)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (if your project uses npm or yarn, otherwise remove this step)
        run: npm install  # or yarn install

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./  # Set the base directory of the project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Your SonarCloud authentication token
